using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace VypusknykPlus.Application.Migrations
{
    /// <inheritdoc />
    public partial class AddChat : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent drops — production may already have these applied
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_Products_Category"";");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_PaymentMethods_Slug"";");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_DeliveryMethods_Slug"";");

            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns
                               WHERE table_name='Products' AND column_name='Category') THEN
                        ALTER TABLE ""Products"" DROP COLUMN ""Category"";
                    END IF;
                END $$;
            ");

            // AlterColumn calls — idempotent, PostgreSQL ignores if already text
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""RibbonPrintColors"" ALTER COLUMN ""Slug"" TYPE text;
                    ALTER TABLE ""RibbonPrintColors"" ALTER COLUMN ""Name"" TYPE text;
                    ALTER TABLE ""RibbonPrintColors"" ALTER COLUMN ""Hex""  TYPE text;
                    ALTER TABLE ""RibbonMaterials""   ALTER COLUMN ""Slug"" TYPE text;
                    ALTER TABLE ""RibbonMaterials""   ALTER COLUMN ""Name"" TYPE text;
                    ALTER TABLE ""RibbonFonts""       ALTER COLUMN ""Slug""       TYPE text;
                    ALTER TABLE ""RibbonFonts""       ALTER COLUMN ""Name""       TYPE text;
                    ALTER TABLE ""RibbonFonts""       ALTER COLUMN ""FontFamily"" TYPE text;
                    ALTER TABLE ""RibbonColors""      ALTER COLUMN ""Slug""         TYPE text;
                    ALTER TABLE ""RibbonColors""      ALTER COLUMN ""Name""         TYPE text;
                    ALTER TABLE ""RibbonColors""      ALTER COLUMN ""Hex""          TYPE text;
                    ALTER TABLE ""RibbonColors""      ALTER COLUMN ""SecondaryHex"" TYPE text;
                    ALTER TABLE ""PaymentMethods""    ALTER COLUMN ""Slug"" TYPE text;
                    ALTER TABLE ""PaymentMethods""    ALTER COLUMN ""Name"" TYPE text;
                    ALTER TABLE ""DeliveryMethods""   ALTER COLUMN ""Slug"" TYPE text;
                    ALTER TABLE ""DeliveryMethods""   ALTER COLUMN ""Name"" TYPE text;
                EXCEPTION WHEN OTHERS THEN NULL;
                END $$;
            ");

            // AddColumn — only if not already present
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                                   WHERE table_name='Products' AND column_name='CategoryId') THEN
                        ALTER TABLE ""Products"" ADD COLUMN ""CategoryId"" bigint NOT NULL DEFAULT 1;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                                   WHERE table_name='Products' AND column_name='SubcategoryId') THEN
                        ALTER TABLE ""Products"" ADD COLUMN ""SubcategoryId"" bigint NULL;
                    END IF;
                END $$;
            ");

            // Tables that may already exist on production — wrap in IF NOT EXISTS
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ProductCategories"" (
                    ""Id"" bigint NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Order"" integer NOT NULL,
                    CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                INSERT INTO ""ProductCategories"" (""Id"", ""Name"", ""Order"") VALUES
                    (1, 'Стрічки', 1), (2, 'Медалі', 2), (3, 'Грамоти', 3), (4, 'Аксесуари', 4)
                ON CONFLICT DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ProductSubcategories"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""CategoryId"" bigint NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Order"" integer NOT NULL,
                    CONSTRAINT ""PK_ProductSubcategories"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ProductSubcategories_ProductCategories_CategoryId""
                        FOREIGN KEY (""CategoryId"") REFERENCES ""ProductCategories"" (""Id"") ON DELETE RESTRICT
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ConstructorForcedTexts"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""TriggerType"" text NOT NULL, ""TriggerSlug"" text NOT NULL,
                    ""TargetField"" text NOT NULL, ""Message"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""IsDeleted"" boolean NOT NULL,
                    CONSTRAINT ""PK_ConstructorForcedTexts"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ConstructorForcedTextValues"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""RuleId"" bigint NOT NULL, ""Value"" text NOT NULL,
                    CONSTRAINT ""PK_ConstructorForcedTextValues"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ConstructorForcedTextValues_ConstructorForcedTexts_RuleId""
                        FOREIGN KEY (""RuleId"") REFERENCES ""ConstructorForcedTexts"" (""Id"") ON DELETE CASCADE
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ConstructorIncompatibilities"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""TypeA"" text NOT NULL, ""SlugA"" text NOT NULL, ""TypeB"" text NOT NULL,
                    ""IsWarning"" boolean NOT NULL, ""Message"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""IsDeleted"" boolean NOT NULL,
                    CONSTRAINT ""PK_ConstructorIncompatibilities"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ConstructorIncompatibilityTargets"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""RuleId"" bigint NOT NULL, ""SlugB"" text NOT NULL,
                    CONSTRAINT ""PK_ConstructorIncompatibilityTargets"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ConstructorIncompatibilityTargets_ConstructorIncompatibilit~""
                        FOREIGN KEY (""RuleId"") REFERENCES ""ConstructorIncompatibilities"" (""Id"") ON DELETE CASCADE
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""RibbonEmblems"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL, ""Slug"" text NOT NULL,
                    ""SvgKeyLeft"" text NULL, ""SvgKeyRight"" text NULL,
                    ""IsActive"" boolean NOT NULL, ""SortOrder"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""IsDeleted"" boolean NOT NULL,
                    CONSTRAINT ""PK_RibbonEmblems"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""RibbonPrintTypes"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL, ""Slug"" text NOT NULL,
                    ""PriceModifier"" numeric NOT NULL,
                    ""IsActive"" boolean NOT NULL, ""SortOrder"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""IsDeleted"" boolean NOT NULL,
                    CONSTRAINT ""PK_RibbonPrintTypes"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                                   WHERE table_name='Products' AND column_name='CategoryId') THEN
                        UPDATE ""Products"" SET ""CategoryId"" = 1 WHERE ""CategoryId"" = 0;
                    END IF;
                END $$;
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Products_CategoryId""   ON ""Products"" (""CategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_Products_SubcategoryId"" ON ""Products"" (""SubcategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_ProductSubcategories_CategoryId"" ON ""ProductSubcategories"" (""CategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_ConstructorForcedTextValues_RuleId"" ON ""ConstructorForcedTextValues"" (""RuleId"");
                CREATE INDEX IF NOT EXISTS ""IX_ConstructorIncompatibilityTargets_RuleId"" ON ""ConstructorIncompatibilityTargets"" (""RuleId"");
            ");

            // === Chat tables — always new ===
            migrationBuilder.CreateTable(
                name: "ChatConversations",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    LastMessageAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsClosedByAdmin = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatConversations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ChatConversations_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ChatMessages",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ConversationId = table.Column<long>(type: "bigint", nullable: false),
                    SenderType = table.Column<int>(type: "integer", nullable: false),
                    SenderId = table.Column<long>(type: "bigint", nullable: false),
                    Text = table.Column<string>(type: "text", nullable: false),
                    SentAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsRead = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatMessages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ChatMessages_ChatConversations_ConversationId",
                        column: x => x.ConversationId,
                        principalTable: "ChatConversations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ChatConversations_UserId",
                table: "ChatConversations",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_ChatMessages_ConversationId",
                table: "ChatMessages",
                column: "ConversationId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Products_ProductCategories_CategoryId",
                table: "Products");

            migrationBuilder.DropForeignKey(
                name: "FK_Products_ProductSubcategories_SubcategoryId",
                table: "Products");

            migrationBuilder.DropTable(
                name: "ChatMessages");

            migrationBuilder.DropTable(
                name: "ConstructorForcedTextValues");

            migrationBuilder.DropTable(
                name: "ConstructorIncompatibilityTargets");

            migrationBuilder.DropTable(
                name: "ProductSubcategories");

            migrationBuilder.DropTable(
                name: "RibbonEmblems");

            migrationBuilder.DropTable(
                name: "RibbonPrintTypes");

            migrationBuilder.DropTable(
                name: "ChatConversations");

            migrationBuilder.DropTable(
                name: "ConstructorForcedTexts");

            migrationBuilder.DropTable(
                name: "ConstructorIncompatibilities");

            migrationBuilder.DropTable(
                name: "ProductCategories");

            migrationBuilder.DropIndex(
                name: "IX_Products_CategoryId",
                table: "Products");

            migrationBuilder.DropIndex(
                name: "IX_Products_SubcategoryId",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "CategoryId",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "SubcategoryId",
                table: "Products");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "RibbonPrintColors",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<decimal>(
                name: "PriceModifier",
                table: "RibbonPrintColors",
                type: "numeric(10,2)",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "RibbonPrintColors",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Hex",
                table: "RibbonPrintColors",
                type: "character varying(20)",
                maxLength: 20,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "RibbonMaterials",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<decimal>(
                name: "PriceModifier",
                table: "RibbonMaterials",
                type: "numeric(10,2)",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "RibbonMaterials",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "RibbonFonts",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "RibbonFonts",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "FontFamily",
                table: "RibbonFonts",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "RibbonColors",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "SecondaryHex",
                table: "RibbonColors",
                type: "character varying(20)",
                maxLength: 20,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "PriceModifier",
                table: "RibbonColors",
                type: "numeric(10,2)",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "RibbonColors",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Hex",
                table: "RibbonColors",
                type: "character varying(20)",
                maxLength: 20,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AddColumn<string>(
                name: "Category",
                table: "Products",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "PaymentMethods",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "PaymentMethods",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Slug",
                table: "DeliveryMethods",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "DeliveryMethods",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 1L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 2L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 3L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 4L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 5L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 6L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 7L,
                column: "Category",
                value: "Medal");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 8L,
                column: "Category",
                value: "Medal");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 9L,
                column: "Category",
                value: "Medal");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 10L,
                column: "Category",
                value: "Certificate");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 11L,
                column: "Category",
                value: "Certificate");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 12L,
                column: "Category",
                value: "Accessory");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 13L,
                column: "Category",
                value: "Accessory");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 14L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 15L,
                column: "Category",
                value: "Ribbon");

            migrationBuilder.CreateIndex(
                name: "IX_Products_Category",
                table: "Products",
                column: "Category");

            migrationBuilder.CreateIndex(
                name: "IX_PaymentMethods_Slug",
                table: "PaymentMethods",
                column: "Slug",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_DeliveryMethods_Slug",
                table: "DeliveryMethods",
                column: "Slug",
                unique: true);
        }
    }
}
