// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VypusknykPlus.Application.Data;

#nullable disable

namespace VypusknykPlus.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408145740_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VypusknykPlus.Application.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<int>("MinOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Popular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Ribbon",
                            Color = "coral",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Класична атласна стрічка з індивідуальним написом. Матеріал — поліестер 100%, ширина 10 см.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Атласна стрічка \"Випускник\"",
                            Popular = true,
                            Price = 45m,
                            Tags = new[] { "випускний", "атлас", "іменна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Ribbon",
                            Color = "blue-yellow",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Двоколірна стрічка в кольорах прапору з можливістю нанесення будь-якого тексту сріблом або золотом.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Стрічка синьо-жовта \"Патріот\"",
                            Popular = true,
                            Price = 50m,
                            Tags = new[] { "випускний", "патріотична", "двоколірна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Ribbon",
                            Color = "gold",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Преміальна золота стрічка з блискучою вишивкою. Відмінний вибір для нагородження відмінників.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Стрічка \"Золотий випускник\"",
                            Popular = true,
                            Price = 65m,
                            Tags = new[] { "відмінник", "золото", "преміум" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Ribbon",
                            Color = "white",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Елегантна біла стрічка — вічна класика для шкільних урочистостей. Чорний або кольоровий друк.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Стрічка біла \"Класика\"",
                            Popular = false,
                            Price = 40m,
                            Tags = new[] { "класика", "біла", "елегантна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ribbon",
                            Color = "red",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Яскраво-червона стрічка для переможців олімпіад та конкурсів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка червона \"Переможець\"",
                            Popular = false,
                            Price = 48m,
                            Tags = new[] { "олімпіада", "перемога", "конкурс" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Ribbon",
                            Color = "purple",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Нестандартний вибір для творчих заходів, театральних фестивалів та мистецьких конкурсів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка фіолетова \"Творчість\"",
                            Popular = false,
                            Price = 48m,
                            Tags = new[] { "творчість", "фестиваль", "мистецтво" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Металева медаль на стрічці з гравіюванням імені та року. Діаметр 70 мм, колір на вибір.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Медаль \"Випускник року\"",
                            Popular = true,
                            Price = 85m,
                            Tags = new[] { "медаль", "нагорода", "гравіювання" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Класична шкільна медаль із зображенням книги та факела. Золоте або срібне покриття.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Медаль \"За відмінне навчання\"",
                            Popular = false,
                            Price = 90m,
                            Tags = new[] { "медаль", "відмінник", "нагорода" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Спортивна медаль для олімпіад і змагань. I, II, III місця. Індивідуальна гравіювання.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 1,
                            Name = "Медаль \"Переможець олімпіади\"",
                            Popular = false,
                            Price = 95m,
                            Tags = new[] { "олімпіада", "змагання", "місце" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Certificate",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Святкова грамота А4 з іменем, класом та датою. Кольоровий друк на дизайнерському папері.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Грамота \"Випускник\"",
                            Popular = false,
                            Price = 25m,
                            Tags = new[] { "грамота", "диплом", "друк" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Certificate",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Преміальний диплом на картоні з тисненням і стрічкою. Формат A4.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Диплом \"З відзнакою\"",
                            Popular = false,
                            Price = 35m,
                            Tags = new[] { "диплом", "відзнака", "преміум" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accessory",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Комплект для класу: стрічки + медаль + грамота для кожного учня. Знижка 15% від окремих цін.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Набір \"Випускний під ключ\"",
                            Popular = true,
                            Price = 320m,
                            Tags = new[] { "набір", "комплект", "знижка" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accessory",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Металева зірка-підвіска із гравіюванням на замовлення. Можна прикріпити до стрічки або рюкзака.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 1,
                            Name = "Підвіска \"Зірка випускника\"",
                            Popular = false,
                            Price = 55m,
                            Tags = new[] { "підвіска", "зірка", "декор" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Ribbon",
                            Color = "green",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Зелена стрічка з еко-принтом. Підходить для шкільних екологічних заходів та фестивалів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка зелена \"Еко\"",
                            Popular = false,
                            Price = 45m,
                            Tags = new[] { "еко", "зелена", "фестиваль" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Ribbon",
                            Color = "black",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Чорна оксамитова стрічка з золотим написом — для особливих урочистостей і нагороджень.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Стрічка чорна \"Преміум\"",
                            Popular = false,
                            Price = 70m,
                            Tags = new[] { "чорна", "оксамит", "золото" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.SavedDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedDesigns");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.CartItem", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.NamesData", "NamesData", b1 =>
                        {
                            b1.Property<Guid>("CartItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("NamesData");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");

                            b1.OwnsMany("VypusknykPlus.Application.ValueObjects.ClassGroup", "Groups", b2 =>
                                {
                                    b2.Property<Guid>("NamesDataCartItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ClassName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Names")
                                        .IsRequired()
                                        .HasMaxLength(5000)
                                        .HasColumnType("character varying(5000)");

                                    b2.HasKey("NamesDataCartItemId", "Id");

                                    b2.ToTable("CartItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NamesDataCartItemId");
                                });

                            b1.Navigation("Groups");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.ProductSnapshot", "ProductSnapshot", b1 =>
                        {
                            b1.Property<Guid>("CartItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Color")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("ProductSnapshot");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RibbonCustomization", "RibbonCustomization", b1 =>
                        {
                            b1.Property<Guid>("CartItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("DesignName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("EmblemKey")
                                .HasColumnType("integer");

                            b1.Property<string>("ExtraTextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("MainText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("RibbonCustomization");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");
                        });

                    b.Navigation("NamesData");

                    b.Navigation("Product");

                    b.Navigation("ProductSnapshot");

                    b.Navigation("RibbonCustomization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.DeliveryInfo", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Warehouse")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RecipientInfo", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.OrderItem", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.RefreshToken", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.SavedDesign", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("SavedDesigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RibbonState", "State", b1 =>
                        {
                            b1.Property<Guid>("SavedDesignId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("EmblemKey")
                                .HasColumnType("integer");

                            b1.Property<string>("ExtraTextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("MainText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("SavedDesignId");

                            b1.ToTable("SavedDesigns");

                            b1.ToJson("State");

                            b1.WithOwner()
                                .HasForeignKey("SavedDesignId");
                        });

                    b.Navigation("State")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavedDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
