// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VypusknykPlus.Application.Data;

#nullable disable

namespace VypusknykPlus.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421095202_FixStockProductIdAutoGenerate")]
    partial class FixStockProductIdAutoGenerate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GuestToken")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuestToken");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<int>("MinOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Popular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Ribbon",
                            Color = "coral",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Класична атласна стрічка з індивідуальним написом. Матеріал — поліестер 100%, ширина 10 см.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Атласна стрічка \"Випускник\"",
                            Popular = true,
                            Price = 45m,
                            Tags = new[] { "випускний", "атлас", "іменна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Ribbon",
                            Color = "blue-yellow",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Двоколірна стрічка в кольорах прапору з можливістю нанесення будь-якого тексту сріблом або золотом.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Стрічка синьо-жовта \"Патріот\"",
                            Popular = true,
                            Price = 50m,
                            Tags = new[] { "випускний", "патріотична", "двоколірна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Ribbon",
                            Color = "gold",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Преміальна золота стрічка з блискучою вишивкою. Відмінний вибір для нагородження відмінників.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Стрічка \"Золотий випускник\"",
                            Popular = true,
                            Price = 65m,
                            Tags = new[] { "відмінник", "золото", "преміум" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Ribbon",
                            Color = "white",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Елегантна біла стрічка — вічна класика для шкільних урочистостей. Чорний або кольоровий друк.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 10,
                            Name = "Стрічка біла \"Класика\"",
                            Popular = false,
                            Price = 40m,
                            Tags = new[] { "класика", "біла", "елегантна" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Ribbon",
                            Color = "red",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Яскраво-червона стрічка для переможців олімпіад та конкурсів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка червона \"Переможець\"",
                            Popular = false,
                            Price = 48m,
                            Tags = new[] { "олімпіада", "перемога", "конкурс" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Ribbon",
                            Color = "purple",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Нестандартний вибір для творчих заходів, театральних фестивалів та мистецьких конкурсів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка фіолетова \"Творчість\"",
                            Popular = false,
                            Price = 48m,
                            Tags = new[] { "творчість", "фестиваль", "мистецтво" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Металева медаль на стрічці з гравіюванням імені та року. Діаметр 70 мм, колір на вибір.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Медаль \"Випускник року\"",
                            Popular = true,
                            Price = 85m,
                            Tags = new[] { "медаль", "нагорода", "гравіювання" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Класична шкільна медаль із зображенням книги та факела. Золоте або срібне покриття.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Медаль \"За відмінне навчання\"",
                            Popular = false,
                            Price = 90m,
                            Tags = new[] { "медаль", "відмінник", "нагорода" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Medal",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Спортивна медаль для олімпіад і змагань. I, II, III місця. Індивідуальна гравіювання.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 1,
                            Name = "Медаль \"Переможець олімпіади\"",
                            Popular = false,
                            Price = 95m,
                            Tags = new[] { "олімпіада", "змагання", "місце" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Certificate",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Святкова грамота А4 з іменем, класом та датою. Кольоровий друк на дизайнерському папері.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Грамота \"Випускник\"",
                            Popular = false,
                            Price = 25m,
                            Tags = new[] { "грамота", "диплом", "друк" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Certificate",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Преміальний диплом на картоні з тисненням і стрічкою. Формат A4.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Диплом \"З відзнакою\"",
                            Popular = false,
                            Price = 35m,
                            Tags = new[] { "диплом", "відзнака", "преміум" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Accessory",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Комплект для класу: стрічки + медаль + грамота для кожного учня. Знижка 15% від окремих цін.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 1,
                            Name = "Набір \"Випускний під ключ\"",
                            Popular = true,
                            Price = 320m,
                            Tags = new[] { "набір", "комплект", "знижка" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Accessory",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Металева зірка-підвіска із гравіюванням на замовлення. Можна прикріпити до стрічки або рюкзака.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 1,
                            Name = "Підвіска \"Зірка випускника\"",
                            Popular = false,
                            Price = 55m,
                            Tags = new[] { "підвіска", "зірка", "декор" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Ribbon",
                            Color = "green",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Зелена стрічка з еко-принтом. Підходить для шкільних екологічних заходів та фестивалів.",
                            IsDeleted = false,
                            IsNew = true,
                            MinOrder = 10,
                            Name = "Стрічка зелена \"Еко\"",
                            Popular = false,
                            Price = 45m,
                            Tags = new[] { "еко", "зелена", "фестиваль" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Ribbon",
                            Color = "black",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Чорна оксамитова стрічка з золотим написом — для особливих урочистостей і нагороджень.",
                            IsDeleted = false,
                            IsNew = false,
                            MinOrder = 5,
                            Name = "Стрічка чорна \"Преміум\"",
                            Popular = false,
                            Price = 70m,
                            Tags = new[] { "чорна", "оксамит", "золото" },
                            UpdatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.SavedDesign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedDesigns");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StockCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Стрічки",
                            Order = 1
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Дзвоники",
                            Order = 2
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Прапорці та прапори",
                            Order = 3
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Нагороди та церемонія",
                            Order = 4
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Інше",
                            Order = 5
                        });
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HasColor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("SubcategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("StockProducts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник атлас об'ємний орнамент",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускниця атлас об'ємна орнамент",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник атлас фольга",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускниця атлас фольга",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник атлас кольоровий",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник атлас голограма",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник орнамент (шовк)",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускниця орнамент (шовк)",
                            SubcategoryId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник атлас об'ємний 9 клас",
                            SubcategoryId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник 21 атлас фольга",
                            SubcategoryId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник 21 атлас фольга 9 клас",
                            SubcategoryId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Класний керівник об'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Класний керівник атлас фольга",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Перший вчитель об'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Перший вчитель необ'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Директор об'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 17L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Директор необ'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 18L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Завуч об'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 19L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Завуч необ'ємний",
                            SubcategoryId = 3L
                        },
                        new
                        {
                            Id = 20L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Першокласник об'ємний",
                            SubcategoryId = 4L
                        },
                        new
                        {
                            Id = 21L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Першокласник необ'ємний",
                            SubcategoryId = 4L
                        },
                        new
                        {
                            Id = 22L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник початкової школи об'ємний",
                            SubcategoryId = 5L
                        },
                        new
                        {
                            Id = 23L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник початкової школи необ'ємний",
                            SubcategoryId = 5L
                        },
                        new
                        {
                            Id = 24L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник дошкільного закладу об'ємний",
                            SubcategoryId = 6L
                        },
                        new
                        {
                            Id = 25L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Випускник дошкільного закладу необ'ємний",
                            SubcategoryId = 6L
                        },
                        new
                        {
                            Id = 26L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Гімназист",
                            SubcategoryId = 7L
                        },
                        new
                        {
                            Id = 27L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Відмінник навчання",
                            SubcategoryId = 7L
                        },
                        new
                        {
                            Id = 28L,
                            HasColor = true,
                            HasMaterial = true,
                            Name = "Кращий учень",
                            SubcategoryId = 7L
                        });
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockSubcategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("StockSubcategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Name = "Випускник 11 клас",
                            Order = 1
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Name = "Випускник 9 клас",
                            Order = 2
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Name = "Вчителі та педагоги",
                            Order = 3
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Name = "Першокласник",
                            Order = 4
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Name = "Молодша школа",
                            Order = 5
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 1L,
                            Name = "Дошкільні заклади",
                            Order = 6
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 1L,
                            Name = "Інші стрічки",
                            Order = 7
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 2L,
                            Name = "Дзвоники прості",
                            Order = 1
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 2L,
                            Name = "Дзвоники з бантами",
                            Order = 2
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 2L,
                            Name = "Банти",
                            Order = 3
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 2L,
                            Name = "Великі дзвони",
                            Order = 4
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 3L,
                            Name = "Прапорці прості",
                            Order = 1
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 3L,
                            Name = "Прапори великі",
                            Order = 2
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 3L,
                            Name = "Присоски для прапорців",
                            Order = 3
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 4L,
                            Name = "Грамоти",
                            Order = 1
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 4L,
                            Name = "Кубки",
                            Order = 2
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 4L,
                            Name = "Значки",
                            Order = 3
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 4L,
                            Name = "Запрошення",
                            Order = 4
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 4L,
                            Name = "Бутун'єрки",
                            Order = 5
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 5L,
                            Name = "Мотки тканинні",
                            Order = 1
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 5L,
                            Name = "Маски",
                            Order = 2
                        });
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("VariantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("VariantId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Material", "Color")
                        .IsUnique();

                    b.ToTable("StockVariants");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.CartItem", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.NamesData", "NamesData", b1 =>
                        {
                            b1.Property<long>("CartItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("NamesData");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");

                            b1.OwnsMany("VypusknykPlus.Application.ValueObjects.ClassGroup", "Groups", b2 =>
                                {
                                    b2.Property<long>("NamesDataCartItemId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ClassName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Names")
                                        .IsRequired()
                                        .HasMaxLength(5000)
                                        .HasColumnType("character varying(5000)");

                                    b2.HasKey("NamesDataCartItemId", "Id");

                                    b2.ToTable("CartItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NamesDataCartItemId");
                                });

                            b1.Navigation("Groups");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RibbonCustomization", "RibbonCustomization", b1 =>
                        {
                            b1.Property<long>("CartItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("DesignName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("EmblemKey")
                                .HasColumnType("integer");

                            b1.Property<string>("ExtraTextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("MainText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("RibbonCustomization");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.ProductSnapshot", "ProductSnapshot", b1 =>
                        {
                            b1.Property<long>("CartItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Color")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.ToJson("ProductSnapshot");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");
                        });

                    b.Navigation("NamesData");

                    b.Navigation("Product");

                    b.Navigation("ProductSnapshot");

                    b.Navigation("RibbonCustomization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.DeliveryInfo", "Delivery", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Warehouse")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RecipientInfo", "Recipient", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.OrderItem", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.NamesData", "NamesData", b1 =>
                        {
                            b1.Property<long>("OrderItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.ToJson("NamesData");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");

                            b1.OwnsMany("VypusknykPlus.Application.ValueObjects.ClassGroup", "Groups", b2 =>
                                {
                                    b2.Property<long>("NamesDataOrderItemId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ClassName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Names")
                                        .IsRequired()
                                        .HasMaxLength(5000)
                                        .HasColumnType("character varying(5000)");

                                    b2.HasKey("NamesDataOrderItemId", "Id");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NamesDataOrderItemId");
                                });

                            b1.Navigation("Groups");
                        });

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RibbonCustomization", "RibbonCustomization", b1 =>
                        {
                            b1.Property<long>("OrderItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("DesignName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("EmblemKey")
                                .HasColumnType("integer");

                            b1.Property<string>("ExtraTextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("MainText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.ToJson("RibbonCustomization");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("NamesData");

                    b.Navigation("Order");

                    b.Navigation("RibbonCustomization");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.ProductImage", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.RefreshToken", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.SavedDesign", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.User", "User")
                        .WithMany("SavedDesigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VypusknykPlus.Application.ValueObjects.RibbonState", "State", b1 =>
                        {
                            b1.Property<long>("SavedDesignId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("EmblemKey")
                                .HasColumnType("integer");

                            b1.Property<string>("ExtraTextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("MainText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("SavedDesignId");

                            b1.ToTable("SavedDesigns");

                            b1.ToJson("State");

                            b1.WithOwner()
                                .HasForeignKey("SavedDesignId");
                        });

                    b.Navigation("State")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockProduct", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.StockSubcategory", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockSubcategory", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.StockCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockTransaction", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.StockVariant", "Variant")
                        .WithMany("Transactions")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockVariant", b =>
                {
                    b.HasOne("VypusknykPlus.Application.Entities.StockProduct", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockCategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockProduct", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockSubcategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.StockVariant", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VypusknykPlus.Application.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavedDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
